stages:
  - sys-deps
  - update-application

variables:
  DEBIAN_FRONTEND: "noninteractive"
  SSH_HOST: $SSH_HOST
  SSH_USERNAME: $SSH_USERNAME
  SSH_PRIV_KEY: $SSH_PRIV_KEY
  HOST: $HOST

before_script:
  - apt-get update -qq
  - apt-get install -qqy sshpass

sys-deps:
  stage: sys-deps
  image: ubuntu:latest
  script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y php zip git
    - apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIV_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - scp -P 22 conf/apache.conf $SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST -p 22 << 'EOF'
        echo "updating system"
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y php zip git
        echo "installing apache"
        cd /etc/apache2/sites-available
        sudo cp /home/$SSH_USERNAME/apache.conf /etc/apache2/sites-available/000-default.conf
        sudo rm -rf /home/$SSH_USERNAME/apache.conf
        sudo a2enmod rewrite
        sudo a2enmod headers
        sudo systemctl restart apache2
        echo "installing composer"
        cd ~
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === 'edb40769019ccf227279e3bdd1f5b2e9950eb000c3233ee85148944e555d97be3ea4f40c3c2fe73b22f875385f6a5155') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        sudo mv composer.phar /usr/local/bin/composer
      EOF

update-application:
  stage: update-application
  image: ubuntu:latest
  script:
    - apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIV_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - scp -r -P 22 . $SSH_USERNAME@$SSH_HOST:/var/www/html
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST -p 22 << 'EOF'
        cd /var/www/html
        touch .env
        > .env 
        echo "HOST=$HOST" >> .env
        composer install
      EOF